spring:
  application:
    name: api-gateway
zuul:
  #全部服务忽略敏感头(全部服务都可传递cookie),这样不用每个单独设置了
  sensitive-headers: 
  routes:
    #这里的myProduct:可以随便写,比如aaaa:
    #/myProduct/1.0/product/order -> /product/1.0/product/order
    myProduct:
      path: /myProduct/**
      serviceId: product
      #设置不过滤掉cookie,默认会过滤,不会传递,将下值设置为空即可
      sensitiveHeaders: 
    #简洁写法
    #product: /myProduct/**
  #排除某些路由,无法外部访问
  ignored-patterns:
    # - /**/1.0/product/order
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
management:
  security:
    enabled: false
ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
server:
  port: 9092
env:
  dev
