spring:
  application:
    name: api-gateway
zuul:
  routes:
    #这里的myProduct:可以随便写,比如aaaa:
    #/myProduct/1.0/product/order -> /product/1.0/product/order
    #myProduct:
    #  path: /myProduct/**
    #  serviceId: product
    #简洁写法
    product: /myProduct/**
  #排除某些路由,无法外部访问
  ignored-patterns:
    - /**/1.0/product/order
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
server:
  port: 9092
env:
  dev
